name: hitnotes
description: An application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^6.0.6
  equatable: ^1.2.5
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.3
  firebase_storage: ^4.0.1
  cloud_functions: ^0.7.0+1
  flame: 0.28.0
  dart_midi: ^1.0.1
  #soundpool: ^1.1.2
  soundpool:
    git:
      url: https://github.com/cuong0993/soundpool.git
      path: soundpool
  soundpool_platform_interface:
    git:
      url: https://github.com/cuong0993/soundpool.git
      path: soundpool_platform_interface
  percent_indicator: ^2.1.7+4
  cupertino_icons: ^1.0.0
  json_annotation: ^3.1.0
  flutter_cache_manager_firebase: ^1.0.1
  cached_network_image: ^2.3.3
  shared_preferences: ^0.5.12+2
  in_app_review: ^1.0.1+1
  intl: ^0.16.1
  flutter_email_sender: ^3.0.1
  package_info: ^0.4.3
  device_info: ^1.0.0
  share: ^0.6.5+4
  firebase_dynamic_links: ^0.6.1
  google_sign_in: ^4.5.5
  flutter_facebook_login: ^3.0.0
  firebase_performance: ^0.4.1
  rxdart: ^0.24.1
  firebase_crashlytics: ^0.2.3+1

dev_dependencies:
  pedantic: ^1.9.2
  build_runner: ^1.10.3
  json_serializable: ^3.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
