name: hitnotes

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^6.0.6
  equatable: ^1.2.5
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  cloud_functions: ^0.9.0
  flame: 0.28.0
  dart_midi: ^1.0.1
  percent_indicator: ^2.1.7+4
  cupertino_icons: ^1.0.0
  built_value: ^7.1.0
  built_collection: ^4.2.2
  flutter_cache_manager: ^2.1.1
  cached_network_image: ^2.5.0
  shared_preferences: ^0.5.12+2
  in_app_review: ^1.0.1+1
  intl: ^0.16.1
  flutter_email_sender: ^4.0.0
  package_info: ^0.4.3
  device_info: ^1.0.0
  share: ^0.6.5+4
  firebase_dynamic_links: ^0.7.0+1
  google_sign_in: ^4.5.8
  flutter_facebook_login: ^3.0.0
  rxdart: ^0.25.0

dev_dependencies:
  pedantic: ^1.9.2
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
  localizely:
    project_id: 12c28e7e-0600-442d-8f23-3ee5a71d49f4
