name: hitnotes

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^7.0.0-nullsafety.4
  equatable: ^2.0.0
  cloud_firestore: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.0
  cloud_functions: ^1.0.0
  flame:
    git:
      url: https://github.com/flame-engine/flame
      ref: null-safety
  dart_midi:
    git:
      url: https://github.com/cuong0993/dart_midi
  cupertino_icons: ^1.0.2
  built_value: ^8.0.2
  built_collection: ^5.0.0
  flutter_cache_manager: ^3.0.0-nullsafety.1
  shared_preferences: ^2.0.3
  in_app_review: ^2.0.1
  intl: ^0.17.0
  mailto: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.2
  package_info: ^2.0.0
  device_info: ^2.0.0
  google_sign_in: ^5.0.0
  flutter_facebook_auth: ^3.0.0-nullsafety.0
  rxdart: ^0.26.0
  sprintf: ^6.0.0

dev_dependencies:
  pedantic: ^1.9.2
  build_runner: ^1.11.5
  built_value_generator: ^8.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
